import 'package:flutter/material.dart';
import '../providers/app_state.dart';

class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // General & Navigation
      'home': 'Home',
      'cart': 'Cart',
      'wallet': 'Wallet',
      'profile': 'Profile',
      'my_profile': 'My Profile',
      'settings': 'Settings',
      'language': 'Language',
      'select_lang': 'Select Language',
      'dark_mode': 'Dark Mode',
      
      // Brand
      'logo_name': 'Ghar Ka Khana',
      'delivering_love': 'Delivering love',
      
      // Auth & Profile
      'auth_login': 'Login',
      'auth_signup': 'Sign Up',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'save': 'Save',
      'member': 'Member',
      'guest_mode': 'Guest Mode',
      'edit_name': 'Edit Name',
      'account_details': 'Account Details',
      'email': 'Email',
      'phone_number': 'Phone Number',
      'change_password': 'Change Password',
      'reset_pass': 'Reset Password',
      'send_link': 'Send Link',
      'pass_reset_sent': 'Password reset email sent!',
      'profile_updated': 'Profile updated successfully!',
      'signin_to_edit': 'Please sign in to edit your profile',
      'delete_account': 'Delete Account',
      
      // Assets & Media
      'choose_photo': 'Choose Profile Photo',
      'take_photo': 'Take Photo',
      'gallery': 'Choose from Gallery',
      'remove_photo': 'Remove Photo',
      'no_photo': 'No Photo',
      
      // Kitchen & Menu
      'all_kitchens': 'All Kitchens Near You',
      'no_kitchens': 'No kitchens available yet',
      'entering_kitchen': 'Entering Kitchen...',
      'today_menu': "Today's Menu",
      'food_menu': 'Food Menu',
      'special_items': "Today's Specials",
      'special': 'Special',
      'all_items': 'All Items',
      'items': 'items',
      'add': 'ADD',
      'veg': 'Veg',
      'non_veg': 'Non-Veg',
      'no_items_available': 'No items available',
      'kitchen_no_items': 'Kitchens haven\'t added items for today yet. Check back soon!',
      'menu_coming_soon': 'Menu coming soon',
      
      // Categories
      'all': 'All',
      'breakfast': 'Breakfast',
      'lunch': 'Lunch',
      'dinner': 'Dinner',
      'snacks': 'Snacks',
      'breakfast_items': 'Breakfast Items',
      'lunch_items': 'Lunch Items',
      'dinner_items': 'Dinner Items',
      'snacks_items': 'Snacks Items',
      
      // Reviews & Cart
      'reviews_title': 'What Neighbours Say',
      'rate_experience': 'Rate your experience',
      'write_review': 'Write a review...',
      'view_all': 'View All',
      'view_cart': 'View Cart',
      'orders': 'Orders',
      'my_orders': 'My Orders',
      'basket': 'Basket',
      'my_cart': 'My Cart',
      'proceed_to_checkout': 'Proceed to Checkout',
      
      // Settings & Features
      'addresses': 'Saved Addresses',
      'delivery_addresses': 'My Delivery Addresses',
      'add_new_address': 'Add New Address',
      'notifications': 'Notifications',
      'help_support': 'Help & Support',
      'about_app': 'About Ghar Ka Khana',
      'app_version': 'App Version',
      'premium': 'Premium',
      'manage_subs': 'Manage Subscriptions',
      'ai': 'Maa AI',
      'search_food': 'Search food or kitchens',
      'changing_theme': 'Changing Theme...',
      'changing_language': 'Changing Language...',
      'total': 'Total',
      'open_now': 'Open Now',
      'closed': 'Closed',
      'pure_veg': 'Pure Veg',
      'multi_cuisine': 'Multi-Cuisine',
      'chat_hint': 'Talk to Maa...',
      'order_now': 'Order Now',
      'customer_support': 'Customer Support',
      'mark_as_solved': 'Mark as Solved',
      'ai_assistant': 'AI Assistant',
      'ai_typing': 'AI assistant is typing...',
      'agent_typing': 'Agent is typing...',
      'satisfied': 'Satisfied',
      'not_satisfied': 'Not Satisfied',
      'talk_to_agent': 'Talk to Human Agent',
      'type_message': 'Type your message...',
      'connecting': 'Connecting...',
      'solved_message': 'Your problem is solved.\nThank you for contacting!',
      'ai_welcome': 'Hi! I\'m the AI Assistant. How can I help you today?',
      'ai_fallback': 'I apologize, would you like to talk to a human agent?',
      'ai_satisfied': 'Glad I could help!',
      'camera': 'Camera',
      'gallery_desc': 'Select existing photo',
      'edit': 'Edit',
      'enter': 'Enter',
      'pass_reset_desc': 'We will send a password reset link to your email.',
      'welcome_back': 'Welcome Back!',
      'welcome_desc': 'Sign in to continue to Ghar Ka Khana',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'sign_in': 'Sign In',
      'continue_with_google': 'Continue with Google',
      'dont_have_account': "Don't have an account? ",
      'sign_up': 'Sign Up',
      'continue_as_guest': 'Continue as Guest',
      'or_continue_with': 'or continue with',
      'email_hint': 'Enter your email',
      'password_hint': 'Enter your password',
      'enter_email': 'Please enter your email',
      'invalid_email': 'Please enter a valid email',
      'enter_password': 'Please enter your password',
      'password_short': 'Password must be at least 6 characters',
      'account_suspended': 'Your account has been suspended. Contact support.',
      'kitchen_load_error': 'Unable to load kitchens',
      'check_internet': 'Please check your internet connection.',
      'retry': 'Retry',
      'orders_count': 'Orders',
      'off': 'OFF',
      'insufficient_wallet': 'Wallet payment failed — insufficient balance or error',
      
      // Cart & Order Tracking
      'delivery_time': 'Delivery in 35 mins',
      'pay_failed': 'Payment Failed',
      'order_placed': 'Order Placed!',
      'paid_wallet': 'Paid from your GKK Wallet',
      'paid_razorpay': 'Paid via Razorpay',
      'track_order': 'Track Order',
      'back_home': 'Back to Home',
      'enter_coupon': 'Enter a coupon code',
      'coupon_invalid': 'Invalid or expired coupon',
      'offers_benefits': 'Offers & Benefits',
      'coupon_applied': 'Coupon Applied!',
      'hint_coupon': 'Enter Coupon Code',
      'bill_details': 'Bill Details',
      'item_total': 'Item Total',
      'delivery_fee': 'Delivery Fee',
      'taxes_charges': 'Taxes & Charges',
      'coupon_discount': 'Coupon Discount',
      'to_pay': 'To Pay',
      'wallet_capital': 'Wallet',
      'razorpay_capital': 'Razorpay',
      'upicard': 'UPI / Card',
      'total_capital': 'TOTAL',
      'pay_wallet': 'Pay from Wallet',
      'add_pay': 'Add Money & Pay',
      'pay_razorpay': 'Pay with Razorpay',
      'order_accepted': 'Order Accepted',
      'preparing_food': 'Preparing Your Food',
      'ready_pickup': 'Ready for Pickup',
      'out_for_delivery': 'Out for Delivery',
      'order_delivered': 'Order Delivered',
      'order_completed': 'Order Completed',
      'order_rejected': 'Order Rejected',
      'waiting_accept': 'Waiting for the kitchen to accept your order...',
      'kitchen_accepted': 'The kitchen has accepted your order!',
      'food_cooking': 'Your delicious food is being cooked...',
      'pickup_ready': 'Your order is ready for pickup/delivery!',
      'food_on_way': 'Your food is on its way to you right now!',
      'delivered_enjoy': 'Your order has been delivered. Enjoy!',
      'rejected_msg': 'Unfortunately, the kitchen could not accept your order.',
      'order_progress': 'Order Progress',
      'order_details': 'Order Details',
      'delivery_address_title': 'Delivery Address',
      'order_not_found': 'Order not found',
      'processing': 'Processing',
      'please_wait': 'Please wait...',
      'no_orders': 'No orders yet',
      'no_orders_desc': 'Your orders will appear here',
      'active_orders': 'Active Orders',
      'past_orders': 'Past Orders',
      'order_id_prefix': 'Order #',
      'more_items': 'more',
      'status_pending': 'Pending',
      'status_accepted': 'Accepted',
      'status_preparing': 'Preparing',
      'status_ready': 'Ready',
      'status_completed': 'Completed',
      'status_rejected': 'Rejected',
      'ago_min': 'm ago',
      'ago_hour': 'h ago',
      'ago_day': 'd ago',
      
      // Taglines
      'tagline_breakfast': 'Good Morning!',
      'tagline_dinner': 'Sweet Dreams & Tasty Food',
      'tagline_wallet': 'Managing your Finances...',
      'tagline_premium': 'Experience Luxury Dining',
      'tagline_default': 'Enjoy your Meal!',
      'wallet_balance_title': 'GKK Wallet Balance',
      'use_wallet_desc': 'Use wallet to pay for orders instantly',
      'add_money': 'Add Money',
      'all_transactions': 'All Transactions',
      'my_cash_wallet': 'My Cash Wallet',
      'manage_wallet_desc': 'Manage balance, add money & view history',
      'view': 'View',
      'recent_transactions': 'Recent Transactions',
      'no_transactions': 'No transactions yet',
      'add_money_desc': 'Add money to start using your wallet',
      'how_it_works': 'How GKK Wallet Works',
      'step_add_money': 'Add Money',
      'step_order_food': 'Order Food',
      'step_pay_instantly': 'Pay Instantly',
      'view_all_txns': 'View all %s transactions',
      'today_at': 'Today',
      
      // Address Edit Screen
      'edit_address': 'Edit Address',
      'add_address': 'Add New Address',
      'address_label': 'Address Label',
      'contact_info': 'Contact Information',
      'full_name': 'Full Name',
      'address_details': 'Address Details',
      'street_address': 'Street Address',
      'area': 'Area / Locality',
      'pincode': 'PIN Code',
      'city': 'City',
      'state': 'State',
      'country': 'Country',
      'addr_home': 'Home',
      'addr_work': 'Work',
      'addr_other': 'Other',
      'use_current_location': 'Use Current Location',
      'auto_fill_address': 'Auto-fill address using GPS',
      'set_default': 'Set as Default Address',
      'default_address_desc': 'This will be used as your primary delivery address',
      'save_changes': 'Save Changes',
      'save_address': 'Save Address',
      'delete_address': 'Delete Address',
      'delete_address_confirm': 'Are you sure you want to delete this address?',
      'delete': 'Delete',
    },
    'hi': {
      'home': 'होम',
      'cart': 'कार्ट',
      'wallet': 'बटुआ',
      'profile': 'प्रोफ़ाइल',
      'my_profile': 'मेरी प्रोफ़ाइल',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'select_lang': 'भाषा चुनें',
      'dark_mode': 'डार्क मोड',
      'logo_name': 'घर का खाना',
      'delivering_love': 'प्यार और स्वाद बाँट रहे हैं',
      'auth_login': 'लॉगिन',
      'auth_signup': 'साइन अप',
      'logout': 'लॉगआउट',
      'logout_confirm': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
      'confirm': 'पुष्टि करें',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'member': 'सदस्य',
      'guest_mode': 'अतिथि मोड',
      'edit_name': 'नाम बदलें',
      'account_details': 'खाता विवरण',
      'email': 'ईमेल',
      'phone_number': 'फ़ोन नंबर',
      'change_password': 'पासवर्ड बदलें',
      'reset_pass': 'पासवर्ड रीसेट करें',
      'send_link': 'लिंक भेजें',
      'pass_reset_sent': 'पासवर्ड रीसेट ईमेल भेज दिया गया है!',
      'profile_updated': 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!',
      'signin_to_edit': 'प्रोफ़ाइल संपादित करने के लिए कृपया साइन इन करें',
      'delete_account': 'खाता हटाएं',
      'choose_photo': 'प्रोफ़ाइल फ़ोटो चुनें',
      'take_photo': 'फोटो लें',
      'gallery': 'गैलरी से चुनें',
      'remove_photo': 'फोटो हटाएं',
      'no_photo': 'कोई फ़ोटो नहीं',
      'all_kitchens': 'आपके पास सभी रसोई',
      'no_kitchens': 'अभी कोई रसोई उपलब्ध नहीं है',
      'entering_kitchen': 'रसोई में प्रवेश कर रहे हैं...',
      'today_menu': 'आज का मेनू',
      'food_menu': 'भोजन मेनू',
      'special_items': 'आज के विशेष व्यंजन',
      'special': 'विशेष',
      'all_items': 'सभी व्यंजन',
      'items': 'आइटम',
      'add': 'जोड़ें',
      'veg': 'शाकाहारी',
      'non_veg': 'मांसाहारी',
      'no_items_available': 'कोई आइटम उपलब्ध नहीं है',
      'kitchen_no_items': 'रसोई ने अभी तक आज के लिए कोई आइटम नहीं जोड़ा है। कृपया बाद में देखें!',
      'menu_coming_soon': 'मेनू जल्द आ रहा है',
      'all': 'सभी',
      'breakfast': 'नाश्ता',
      'lunch': 'लंच',
      'dinner': 'डिनर',
      'snacks': 'स्नैक्स',
      'breakfast_items': 'नाश्ते के विकल्प',
      'lunch_items': 'लंच के विकल्प',
      'dinner_items': 'डिनर के विकल्प',
      'snacks_items': 'स्नैक्स के विकल्प',
      'reviews_title': 'पड़ोसी क्या कहते हैं',
      'rate_experience': 'अपना अनुभव साझा करें',
      'write_review': 'एक समीक्षा लिखें...',
      'view_all': 'सभी देखें',
      'view_cart': 'कार्ट देखें',
      'orders': 'आदेश',
      'my_orders': 'मेरे ऑर्डर',
      'basket': 'टोकरी',
      'my_cart': 'मेरी टोकरी',
      'proceed_to_checkout': 'चेकआउट पर जाएँ',
      'addresses': 'पते',
      'delivery_addresses': 'मेरे वितरण पते',
      'add_new_address': 'नया पता जोड़ें',
      'notifications': 'सूचनाएं',
      'help_support': 'सहायता',
      'about_app': 'घर का खाना के बारे में',
      'app_version': 'ऐप संस्करण',
      'premium': 'प्रीमियम',
      'manage_subs': 'सदस्यता प्रबंधित करें',
      'ai': 'मा एआई',
      'search_food': 'खाना या रसोई खोजें',
      'changing_theme': 'थीम बदल रहा है...',
      'changing_language': 'भाषा बदल रहा है...',
      'total': 'कुल',
      'open_now': 'अभी खुला है',
      'closed': 'बंद है',
      'pure_veg': 'शुद्ध शाकाहारी',
      'multi_cuisine': 'मल्टी-कुजीन',
      'chat_hint': 'माँ से बात करो...',
      'order_now': 'अभी ऑर्डर करें',
      'customer_support': 'ग्राहक सहायता',
      'mark_as_solved': 'सुलझा हुआ चिह्नित करें',
      'ai_assistant': 'एआई सहायक',
      'ai_typing': 'एआई सहायक टाइप कर रहा है...',
      'agent_typing': 'एजेंट टाइप कर रहा है...',
      'satisfied': 'संतुष्ट',
      'not_satisfied': 'असंतुष्ट',
      'talk_to_agent': 'एजेंट से बात करें',
      'type_message': 'अपना संदेश लिखें...',
      'connecting': 'जुड़ रहा है...',
      'solved_message': 'आपकी समस्या सुलझ गई है।\nसंपर्क करने के लिए धन्यवाद!',
      'ai_welcome': 'नमस्ते! मैं एआई सहायक हूँ। मैं आपकी कैसे मदद कर सकता हूँ?',
      'ai_fallback': 'क्षमा करें, क्या आप एजेंट से बात करना चाहेंगे?',
      'ai_satisfied': 'खुशी है कि मैं मदद कर सका!',
      'camera': 'कैमरा',
      'gallery_desc': 'मौजूदा फ़ोटो चुनें',
      'edit': 'संपादित करें',
      'enter': 'दर्ज करें',
      'pass_reset_desc': 'हम आपके ईमेल पर पासवर्ड रीसेट लिंक भेजेंगे।',
      'welcome_back': 'वापसी पर स्वागत है!',
      'welcome_desc': 'घर का खाना जारी रखने के लिए साइन इन करें',
      'password': 'पासवर्ड',
      'forgot_password': 'पासवर्ड भूल गए?',
      'sign_in': 'साइन इन करें',
      'continue_with_google': 'गूगल के साथ जारी रखें',
      'dont_have_account': "खाता नहीं है? ",
      'sign_up': 'साइन अप करें',
      'continue_as_guest': 'अतिथि के रूप में जारी रखें',
      'or_continue_with': 'या इसके साथ जारी रखें',
      'email_hint': 'अपना ईमेल दर्ज करें',
      'password_hint': 'अपना पासवर्ड दर्ज करें',
      'enter_email': 'कृपया अपना ईमेल दर्ज करें',
      'invalid_email': 'कृपया एक वैध ईमेल दर्ज करें',
      'enter_password': 'कृपया अपना पासवर्ड दर्ज करें',
      'password_short': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
      'account_suspended': 'आपका खाता निलंबित कर दिया गया है। समर्थन से संपर्क करें।',
      'kitchen_load_error': 'रसोई लोड करने में असमर्थ',
      'check_internet': 'कृपया अपना इंटरनेट कनेक्शन जांचें।',
      'retry': 'पुनः प्रयास करें',
      'orders_count': 'ऑर्डर',
      'off': 'छूट',
      'insufficient_wallet': 'बटुआ भुगतान विफल — अपर्याप्त शेष या त्रुटि',
      
      // Cart & Order Tracking
      'delivery_time': '35 मिनट में डिलीवरी',
      'pay_failed': 'भुगतान विफल',
      'order_placed': 'आदेश दिया गया!',
      'paid_wallet': 'आपके GKK बटुए से भुगतान किया गया',
      'paid_razorpay': 'Razorpay के माध्यम से भुगतान किया गया',
      'track_order': 'ऑर्डर ट्रैक करें',
      'back_home': 'होम पर वापस जाएं',
      'enter_coupon': 'कूपन कोड दर्ज करें',
      'coupon_invalid': 'अमान्य या समाप्त कूपन',
      'offers_benefits': 'ऑफ़र और लाभ',
      'coupon_applied': 'कूपन लागू किया गया!',
      'hint_coupon': 'कूपन कोड दर्ज करें',
      'bill_details': 'बिल विवरण',
      'item_total': 'आइटम कुल',
      'delivery_fee': 'डिलीवरी शुल्क',
      'taxes_charges': 'टैक्स और शुल्क',
      'coupon_discount': 'कूपन छूट',
      'to_pay': 'कुल भुगतान',
      'wallet_capital': 'वॉलेट',
      'razorpay_capital': 'Razorpay',
      'upicard': 'UPI / कार्ड',
      'total_capital': 'कुल',
      'pay_wallet': 'वॉलेट से भुगतान करें',
      'add_pay': 'पैसे जोड़ें और भुगतान करें',
      'pay_razorpay': 'Razorpay से भुगतान करें',
      'order_accepted': 'ऑर्डर स्वीकार कर लिया गया',
      'preparing_food': 'आपका खाना तैयार किया जा रहा है',
      'ready_pickup': 'पिकअप के लिए तैयार',
      'out_for_delivery': 'डिलीवरी के लिए निकला है',
      'order_delivered': 'ऑर्डर दिया गया',
      'order_completed': 'ऑर्डर पूरा हुआ',
      'order_rejected': 'ऑर्डर रद्द कर दिया गया',
      'waiting_accept': 'रसोई द्वारा आपके आदेश को स्वीकार करने की प्रतीक्षा की जा रही है...',
      'kitchen_accepted': 'रसोई ने आपका आदेश स्वीकार कर लिया है!',
      'food_cooking': 'आपका स्वादिष्ट खाना पकाया जा रहा है...',
      'pickup_ready': 'आपका ऑर्डर पिकअप/डिलीवरी के लिए तैयार है!',
      'food_on_way': 'आपका खाना अभी आपके पास आ रहा है!',
      'delivered_enjoy': 'आपका ऑर्डर डिलीवर हो गया है। आनंद लें!',
      'rejected_msg': 'दुर्भाग्य से, रसोई ने आपके आदेश को स्वीकार नहीं किया।',
      'order_progress': 'ऑर्डर की प्रगति',
      'order_details': 'आदेश विवरण',
      'delivery_address_title': 'डिलिवरी का पता',
      'order_not_found': 'ऑर्डर नहीं मिला',
      'processing': 'कार्यवाही हो रही है',
      'please_wait': 'कृपया प्रतीक्षा करें...',
      'no_orders': 'अभी तक कोई ऑर्डर नहीं',
      'no_orders_desc': 'आपके ऑर्डर यहाँ दिखाई देंगे',
      'active_orders': 'सक्रिय ऑर्डर',
      'past_orders': 'पुराने ऑर्डर',
      'order_id_prefix': 'ऑर्डर #',
      'more_items': 'और',
      'status_pending': 'लंबित',
      'status_accepted': 'स्वीकार किया गया',
      'status_preparing': 'तैयार किया जा रहा है',
      'status_ready': 'तैयार',
      'status_completed': 'पूरा हुआ',
      'status_rejected': 'अस्वीकार कर दिया गया',
      'ago_min': 'मिनट पहले',
      'ago_hour': 'घंटे पहले',
      'ago_day': 'दिन पहले',
      
      'tagline_breakfast': 'सुप्रभात!',
      'tagline_dinner': 'शुभ रात्रि और स्वादिष्ट भोजन',
      'tagline_wallet': 'वित्तीय प्रबंधन...',
      'tagline_premium': 'लक्जरी डाइनिंग का अनुभव करें',
      'tagline_default': 'भोजन का आनंद लें!',
      'wallet_balance_title': 'जीकेके वॉलेट बैलेंस',
      'use_wallet_desc': 'तुरंत ऑर्डर के लिए वॉलेट का उपयोग करें',
      'add_money': 'पैसे जोड़ें',
      'all_transactions': 'सभी लेनदेन',
      'my_cash_wallet': 'मेरा कैश वॉलेट',
      'manage_wallet_desc': 'बैलेंस प्रबंधित करें, पैसे जोड़ें और इतिहास देखें',
      'view': 'देखें',
      'recent_transactions': 'हाल के लेनदेन',
      'no_transactions': 'अभी तक कोई लेनदेन नहीं',
      'add_money_desc': 'अपने वॉलेट का उपयोग शुरू करने के लिए पैसे जोड़ें',
      'how_it_works': 'जीकेके वॉलेट कैसे काम करता है',
      'step_add_money': 'पैसे जोड़ें',
      'step_order_food': 'खाना ऑर्डर करें',
      'step_pay_instantly': 'तुरंत भुगतान करें',
      'view_all_txns': 'सभी %s लेनदेन देखें',
      'today_at': 'आज',
      
      // Address Edit Screen
      'edit_address': 'पता संपादित करें',
      'add_address': 'नया पता जोड़ें',
      'address_label': 'पते का लेबल',
      'contact_info': 'संपर्क जानकारी',
      'full_name': 'पूरा नाम',
      'address_details': 'पते का विवरण',
      'street_address': 'गली का पता',
      'area': 'क्षेत्र / मोहल्ला',
      'pincode': 'पिन कोड',
      'city': 'शहर',
      'state': 'राज्य',
      'country': 'देश',
      'addr_home': 'घर',
      'addr_work': 'कार्यालय',
      'addr_other': 'अन्य',
      'use_current_location': 'वर्तमान स्थान का उपयोग करें',
      'auto_fill_address': 'GPS से पता स्वत: भरें',
      'set_default': 'डिफ़ॉल्ट पता सेट करें',
      'default_address_desc': 'यह आपके प्राथमिक डिलीवरी पते के रूप में उपयोग किया जाएगा',
      'save_changes': 'परिवर्तन सहेजें',
      'save_address': 'पता सहेजें',
      'delete_address': 'पता हटाएं',
      'delete_address_confirm': 'क्या आप सच में यह पता हटाना चाहते हैं?',
      'delete': 'हटाएं',
    },
    'bn': {
      'home': 'হোম',
      'cart': 'কার্ট',
      'wallet': 'মানিব্যাগ',
      'profile': 'প্রোফাইল',
      'my_profile': 'আমার প্রোফাইল',
      'settings': 'সেটিংস',
      'language': 'ভাষা',
      'select_lang': 'ভাষা নির্বাচন করুন',
      'dark_mode': 'ডার্ক মোড',
      'logo_name': 'ঘর কা খানা',
      'delivering_love': 'ভালোবাসা পরিবেশন করছি',
      'auth_login': 'লগ ইন',
      'auth_signup': 'সাইন আপ',
      'logout': 'লগআউট',
      'logout_confirm': 'আপনি কি নিশ্চিত যে আপনি লগআউট করতে চান?',
      'confirm': 'নিশ্চিত করুন',
      'cancel': 'বাতিল',
      'save': 'সংরক্ষণ করুন',
      'member': 'সদস্য',
      'guest_mode': 'গেস্ট মোড',
      'edit_name': 'নাম পরিবর্তন করুন',
      'account_details': 'অ্যাকাউন্টের বিবরণ',
      'email': 'ইমেল',
      'phone_number': 'ফোন নম্বর',
      'change_password': 'পাসওয়ার্ড পরিবর্তন',
      'reset_pass': 'পাসওয়ার্ড রিসেট করুন',
      'send_link': 'লিঙ্ক পাঠান',
      'pass_reset_sent': 'পাসওয়ার্ড রিসেট ইমেল পাঠানো হয়েছে!',
      'profile_updated': 'প্রোফাইল সফলভাবে আপডেট করা হয়েছে!',
      'signin_to_edit': 'প্রোফাইল এডিট করতে সাইন ইন করুন',
      'delete_account': 'অ্যাকাউন্ট মুছুন',
      'choose_photo': 'প্রোফাইল ফটো চয়ন করুন',
      'take_photo': 'ছবি তুলুন',
      'gallery': 'গ্যালারি থেকে চয়ন করুন',
      'remove_photo': 'ছবি সরান',
      'no_photo': 'কোন ছবি নেই',
      'all_kitchens': 'আপনার কাছাকাছি সব রান্নাঘর',
      'no_kitchens': 'এখনও কোনো রান্নাঘর পাওয়া যায়নি',
      'entering_kitchen': 'রান্নাঘরে প্রবেশ করছি...',
      'today_menu': 'আজকের মেনু',
      'food_menu': 'খাবার মেনু',
      'special_items': 'আজকের বিশেষ খাবার',
      'special': 'বিশেষ',
      'all_items': 'সব খাবার',
      'items': 'আইটেম',
      'add': 'যোগ করুন',
      'veg': 'নিরামিষ',
      'non_veg': 'আমিষ',
      'no_items_available': 'কোন খাবার পাওয়া যাচ্ছে না',
      'kitchen_no_items': 'রান্নাঘর এখনও আজকের জন্য কোন আইটেম যোগ করেনি। পরে আবার দেখুন!',
      'menu_coming_soon': 'মেনু শীঘ্রই আসছে',
      'all': 'সব',
      'breakfast': 'প্রাতঃরাশ',
      'lunch': 'লাঞ্চ',
      'dinner': 'ডিনার',
      'snacks': 'স্ন্যাকস',
      'breakfast_items': 'প্রাতঃরাশের বিকল্প',
      'lunch_items': 'লাঞ্চের বিকল্প',
      'dinner_items': 'ডিনারের বিকল্প',
      'snacks_items': 'স্ন্যাকসের বিকল্প',
      'reviews_title': 'প্রতিবেশীরা কি বলছে',
      'rate_experience': 'আপনার অভিজ্ঞতা শেয়ার করুন',
      'write_review': 'একটি পর্যালোচনা লিখুন...',
      'view_all': 'সব দেখুন',
      'view_cart': 'কার্ট দেখুন',
      'orders': 'অর্ডার',
      'my_orders': 'আমার অর্ডার',
      'basket': 'বাস্কেট',
      'my_cart': 'আমার বাস্কেট',
      'proceed_to_checkout': 'চেকআউট করুন',
      'addresses': 'ঠিকানা',
      'delivery_addresses': 'আমার ডেলিভারি ঠিকানা',
      'add_new_address': 'নতুন ঠিকানা যোগ করুন',
      'notifications': 'বিজ্ঞপ্তি',
      'help_support': 'সহায়তা',
      'about_app': 'ঘর কা খানা সম্পর্কে',
      'app_version': 'অ্যাপ সংস্করণ',
      'premium': 'প্রিমিয়াম',
      'manage_subs': 'সাবস্ক্রিপশন পরিচালনা',
      'ai': 'মা এআই',
      'search_food': 'খাবার বা রান্নাঘর খুঁজুন',
      'changing_theme': 'থিম পরিবর্তন হচ্ছে...',
      'changing_language': 'ভাষা পরিবর্তন হচ্ছে...',
      'total': 'মোট',
      'open_now': 'এখন খোলা আছে',
      'closed': 'বন্ধ আছে',
      'pure_veg': 'নিরামিষ',
      'multi_cuisine': 'মাল্টি-কুইজিন',
      'chat_hint': 'মায়ের সাথে কথা বলো...',
      'order_now': 'এখনই অর্ডার করুন',
      'customer_support': 'গ্রাহক সহায়তা',
      'mark_as_solved': 'সমাধান হয়েছে চিহ্নিত করুন',
      'ai_assistant': 'AI সহকারী',
      'ai_typing': 'AI সহকারী লিখছে...',
      'agent_typing': 'এজেন্ট লিখছে...',
      'satisfied': 'সন্তুষ্ট',
      'not_satisfied': 'অসন্তুষ্ট',
      'talk_to_agent': 'এজেন্টের সাথে কথা বলুন',
      'type_message': 'আপনার বার্তা লিখুন...',
      'connecting': 'সংযোগ হচ্ছে...',
      'solved_message': 'আপনার সমস্যার সমাধান হয়েছে।\nযোগাযোগ করার জন্য ধন্যবাদ!',
      'ai_welcome': 'হ্যালো! আমি AI সহকারী। আমি আপনাকে কীভাবে সাহায্য করতে পারি?',
      'ai_fallback': 'আমি দুঃখিত, আপনি কি এজেন্টের সাথে কথা বলতে চান?',
      'ai_satisfied': 'সাহায্য করতে পেরে খুশি!',
      'camera': 'ক্যামেরা',
      'gallery_desc': 'বিদ্যমান ছবি নির্বাচন করুন',
      'edit': 'সম্পাদনা করুন',
      'enter': 'লিখুন',
      'pass_reset_desc': 'আমরা আপনার ইমেলে একটি পাসওয়ার্ড রিসেট লিঙ্ক পাঠাব।',
      'welcome_back': 'ফিরে আসার জন্য স্বাগতম!',
      'welcome_desc': 'ঘর কা খানা চালিয়ে যেতে সাইন ইন করুন',
      'password': 'পাসওয়ার্ড',
      'forgot_password': 'পাসওয়ার্ড ভুলে গেছেন?',
      'sign_in': 'সাইন ইন করুন',
      'continue_with_google': 'গুগল দিয়ে চালিয়ে যান',
      'dont_have_account': "অ্যাকাউন্ট নেই? ",
      'sign_up': 'সাইন আপ করুন',
      'continue_as_guest': 'গেস্ট হিসেবে চালিয়ে যান',
      'or_continue_with': 'অথবা এটি দিয়ে চালিয়ে যান',
      'email_hint': 'আপনার ইমেল লিখুন',
      'password_hint': 'আপনার পাসওয়ার্ড লিখুন',
      'enter_email': 'আপনার ইমেল লিখুন দয়া করে',
      'invalid_email': 'একটি বৈধ ইমেল লিখুন দয়া করে',
      'enter_password': 'আপনার পাসওয়ার্ড লিখুন দয়া করে',
      'password_short': 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে',
      'account_suspended': 'আপনার অ্যাকাউন্ট স্থগিত করা হয়েছে। সহায়তার সাথে যোগাযোগ করুন।',
      'kitchen_load_error': 'রান্নাঘর লোড করতে অক্ষম',
      'check_internet': 'আপনার ইন্টারনেট সংযোগ পরীক্ষা করুন দয়া করে।',
      'retry': 'আবার চেষ্টা করুন',
      'orders_count': 'অর্ডার',
      'off': 'ছাড়',
      'insufficient_wallet': 'ওয়ালেট পেমেন্ট ব্যর্থ — অপর্যাপ্ত ব্যালেন্স বা ত্রুটি',
      
      // Cart & Order Tracking
      'delivery_time': '35 মিনিটের মধ্যে ডেলিভারি',
      'pay_failed': 'পেমেন্ট ব্যর্থ হয়েছে',
      'order_placed': 'অর্ডার কার্যকর হয়েছে!',
      'paid_wallet': 'আপনার GKK ওয়ালেট থেকে অর্থ প্রদান করা হয়েছে',
      'paid_razorpay': 'Razorpay এর মাধ্যমে অর্থ প্রদান করা হয়েছে',
      'track_order': 'অর্ডার ট্র্যাক করুন',
      'back_home': 'হোমে ফিরে যান',
      'enter_coupon': 'একটি কুপন কোড লিখুন',
      'coupon_invalid': 'অবৈধ বা মেয়াদোত্তীর্ণ কুপন',
      'offers_benefits': 'অফার এবং সুবিধা',
      'coupon_applied': 'কুপন প্রয়োগ করা হয়েছে!',
      'hint_coupon': 'কুপন কোড লিখুন',
      'bill_details': 'বিলের বিবরণ',
      'item_total': 'মোট আইটেম',
      'delivery_fee': 'ডেলিভারি ফি',
      'taxes_charges': 'ট্যাক্স এবং চার্জ',
      'coupon_discount': 'কুপন ডিসকাউন্ট',
      'to_pay': 'মোট দেয়',
      'wallet_capital': 'ওয়ালেট',
      'razorpay_capital': 'Razorpay',
      'upicard': 'UPI / কার্ড',
      'total_capital': 'মোট',
      'pay_wallet': 'ওয়ালেট থেকে প্রদান করুন',
      'add_pay': 'টাকা যোগ করুন এবং প্রদান করুন',
      'pay_razorpay': 'Razorpay দিয়ে প্রদান করুন',
      'order_accepted': 'অর্ডার গ্রহণ করা হয়েছে',
      'preparing_food': 'আপনার খাবার তৈরি করা হচ্ছে',
      'ready_pickup': 'পিকআপের জন্য প্রস্তুত',
      'order_completed': 'অর্ডার সম্পন্ন',
      'order_delivered': 'অর্ডার পৌঁছে দেওয়া হয়েছে',
      'order_rejected': 'অর্ডার প্রত্যাখ্যাত হয়েছে',
      'waiting_accept': 'রান্নাঘর আপনার অর্ডার গ্রহণ করার জন্য অপেক্ষা করছে...',
      'kitchen_accepted': 'রান্নাঘর আপনার অর্ডার গ্রহণ করেছে!',
      'food_cooking': 'আপনার সুস্বাদু খাবার রান্না করা হচ্ছে...',
      'pickup_ready': 'আপনার অর্ডার পিকআপ/ডেলিভারির জন্য প্রস্তুত!',
      'delivered_enjoy': 'আপনার অর্ডার পৌঁছে দেওয়া হয়েছে। উপভোগ করুন!',
      'rejected_msg': 'দুর্ভাগ্যবশত, রান্নাঘর আপনার অর্ডার গ্রহণ করতে পারেনি।',
      'order_progress': 'অর্ডারের অগ্রগতি',
      'order_details': 'অর্ডারের বিবরণ',
      'delivery_address_title': 'ডেলিভারি ঠিকানা',
      'order_not_found': 'অর্ডার পাওয়া যায়নি',
      'processing': 'প্রক্রিয়া করা হচ্ছে',
      'please_wait': 'দয়া করে অপেক্ষা করুন...',
      'out_for_delivery': 'ডেলিভারির জন্য বেরিয়েছে',
      'food_on_way': 'আপনার খাবার আপনার কাছে পৌঁছাচ্ছে!',
      'no_orders': 'এখনও কোনো অর্ডার নেই',
      'no_orders_desc': 'আপনার অর্ডার এখানে প্রদর্শিত হবে',
      'active_orders': 'সক্রিয় অর্ডার',
      'past_orders': 'আগের অর্ডার',
      'order_id_prefix': 'অর্ডার #',
      'more_items': 'আরও',
      'status_pending': 'অপেক্ষমান',
      'status_accepted': 'গৃহীত',
      'status_preparing': 'তৈরি হচ্ছে',
      'status_ready': 'প্রস্তুত',
      'status_completed': 'সম্পন্ন',
      'status_rejected': 'প্রত্যাখ্যাত',
      'ago_min': 'মি আগে',
      'ago_hour': 'ঘ আগে',
      'ago_day': 'দিন আগে',
      
      'tagline_breakfast': 'সুপ্রভাত!',
      'tagline_dinner': 'শুভ রাত্রি এবং সুস্বাদু খাবার',
      'tagline_wallet': 'আপনার অর্থ পরিচালনা করা হচ্ছে...',
      'tagline_premium': 'বিলাসবহুল ডাইনিং অনুভব করুন',
      'tagline_default': 'আপনার খাবার উপভোগ করুন!',
      'wallet_balance_title': 'জিকেকে ওয়ালেট ব্যালেন্স',
      'use_wallet_desc': 'তাত্ক্ষণিকভাবে অর্ডারের জন্য ওয়ালেট ব্যবহার করুন',
      'add_money': 'টাকা যোগ করুন',
      'all_transactions': 'সমস্ত লেনদেন',
      'my_cash_wallet': 'আমার ক্যাশ ওয়ালেট',
      'manage_wallet_desc': 'ব্যালেন্স পরিচালনা করুন, টাকা যোগ করুন এবং ইতিহাস দেখুন',
      'view': 'দেখুন',
      'recent_transactions': 'সাম্প্রতিক লেনদেন',
      'no_transactions': 'এখনও কোনো লেনদেন নেই',
      'add_money_desc': 'আপনার ওয়ালেট ব্যবহার শুরু করতে টাকা যোগ করুন',
      'how_it_works': 'জিকেকে ওয়ালেট কীভাবে কাজ করে',
      'step_add_money': 'টাকা যোগ করুন',
      'step_order_food': 'খাবার অর্ডার করুন',
      'step_pay_instantly': 'তাত্ক্ষণিক পেমেন্ট',
      'view_all_txns': 'সমস্ত %s লেনদেন দেখুন',
      'today_at': 'আজ',
      
      // Address Edit Screen
      'edit_address': 'ঠিকানা সম্পাদনা করুন',
      'add_address': 'নতুন ঠিকানা যোগ করুন',
      'address_label': 'ঠিকানার লেবেল',
      'contact_info': 'যোগাযোগের তথ্য',
      'full_name': 'পুরো নাম',
      'address_details': 'ঠিকানার বিবরণ',
      'street_address': 'রাস্তার ঠিকানা',
      'area': 'এলাকা / মহল্লা',
      'pincode': 'পিন কোড',
      'city': 'শহর',
      'state': 'রাজ্য',
      'country': 'দেশ',
      'addr_home': 'বাড়ি',
      'addr_work': 'কর্মস্থল',
      'addr_other': 'অন্যান্য',
      'use_current_location': 'বর্তমান অবস্থান ব্যবহার করুন',
      'auto_fill_address': 'GPS দিয়ে ঠিকানা স্বয়ংক্রিয়ভাবে পূরণ করুন',
      'set_default': 'ডিফল্ট ঠিকানা সেট করুন',
      'default_address_desc': 'এটি আপনার প্রধান ডেলিভারি ঠিকানা হিসাবে ব্যবহৃত হবে',
      'save_changes': 'পরিবর্তন সংরক্ষণ করুন',
      'save_address': 'ঠিকানা সংরক্ষণ করুন',
      'delete_address': 'ঠিকানা মুছুন',
      'delete_address_confirm': 'আপনি কি নিশ্চিত যে আপনি এই ঠিকানাটি মুছতে চান?',
      'delete': 'মুছুন',
    },
  };

  static String of(BuildContext context, String key) {
    final languageCode = AppState().locale.languageCode;
    final Map<String, String>? dict = _localizedValues[languageCode] ?? _localizedValues['en'];
    return dict?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

extension LocalizedString on String {
  String tr(BuildContext context) {
    return AppLocalizations.of(context, this);
  }
}
