default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Store Internal track"
  lane :deploy_internal do
    # 1. Build the Android App Bundle
    sh("cd ../.. && flutter build appbundle --release")
    
    # 2. Upload to Google Play Internal Track
    retries = 0
    begin
      upload_to_play_store(
        track: 'internal',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        json_key: 'fastlane/play_store_service_account.json',
        version_name: '1.6.3',
        timeout: 600
      )
    rescue => e
      if retries < 2
        retries += 1
        UI.error("Upload failed with error: #{e.message}. Retrying (#{retries}/2)...")
        sleep(5)
        retry
      else
        UI.user_error!("Upload failed after multiple attempts: #{e.message}")
      end
    end
  end

  desc "Deploy a new version to the Google Play Store Production track"
  lane :deploy_production do
    # 1. Build the Android App Bundle
    sh("cd ../.. && flutter build appbundle --release")
    
    # 2. Upload to Google Play Production Track
    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end
end
